% =========================================================================
% Digital Signal Processing Laboratory
% Analysis of LTI Systems, Linear Convolution, and BIBO Stability
% =========================================================================
clear; clc; close all;

%% Experiment 1: Non-linear System Shift
% Demonstrating the effect of a DC offset on a simple sinusoidal signal.
n_ex1 = 0:100;
x_nonlinear = sin(2*pi*0.05*n_ex1) + 10; % Input signal shifted by +10 DC

%% Experiment 2: LTI System - Impulse Response (Using impz)
figure('Name', 'Impulse Response using impz');
N = 45;
% System defined by difference equation coefficients
num = [0.9 -0.45 0.35 0.002];
den = [1 0.71 -0.46 -0.62];

% Compute and visualize the impulse response natively using impz
y_impz = impz(num, den, N);
stem(y_impz, 'filled');
xlabel('Time index n'); 
ylabel('Amplitude');
title('Impulse Response (using impz)'); 
grid on;

%% Experiment 3: LTI System - Impulse Response (Using filter)
figure('Name', 'Impulse Response using filter');
N_filter = 40;

% Replicating impz behavior by passing a Kronecker delta through the filter
x_impulse = [1, zeros(1, N_filter-1)];
y_filter_impulse = filter(num, den, x_impulse);

stem(0:N_filter-1, y_filter_impulse, 'filled');
xlabel('Time index n');
ylabel('Amplitude');
title('Impulse Response (using filter)');
grid on;

%% Experiment 4: LTI System - Step Response
figure('Name', 'Step Response');

% Evaluating the system's accumulation behavior via a step input
x_step = ones(1, N_filter);
y_step = filter(num, den, x_step);

stem(0:N_filter-1, y_step, 'filled');
xlabel('Time index n');
ylabel('Amplitude');
title('Step Response (using filter)');
grid on;

%% Experiment 5: System Response to Sinusoidal Inputs (Non-Zero ICs)
figure('Name', 'Sinusoidal Input Response');
n = 0:40;
a = 3.0; 
b = -2.0;
x_sin = a*sin(2*pi*0.1*n) + b*sin(2*pi*0.4*n);

% Demonstrating how non-zero initial conditions violate LTI properties
ic = [1, 0, 0]; % 3rd-order initial condition states
y_sin_response = filter(num, den, x_sin, ic);

stem(n, y_sin_response, 'filled');
xlabel('Time index n'); 
ylabel('Amplitude');
title('System Response with Non-Zero Initial Conditions'); 
grid on;

%% Experiment 6: Convolution vs. Filtering
figure('Name', 'Convolution vs Filtering');
h_conv = [3 2 1 -2 1 0 -4 0 3];                   % System impulse response
x_conv = [1 -2 3 -4 3 2 1 3 2 -1 2 -3 4 2 1];     % Arbitrary input sequence

% Part A: Standard linear convolution
y_conv = conv(h_conv, x_conv);
n_conv = 0:22; % Resulting length: L_x + L_h - 1 (15 + 9 - 1 = 23)

subplot(2,1,1);
stem(n_conv, y_conv, 'filled');
xlabel('Time index n'); 
ylabel('Amplitude');
title('Output Obtained by Convolution'); 
grid on;

% Part B: Replicating convolution via zero-padded filtering
% Padding the length-15 input with 8 zeros to reach length 23
x1_conv = [x_conv, zeros(1,8)]; 
y1_filter = filter(h_conv, 1, x1_conv);

subplot(2,1,2);
stem(n_conv, y1_filter, 'filled');
xlabel('Time index n'); 
ylabel('Amplitude');
title('Output Generated by Filtering'); 
grid on;

%% Experiment 7: BIBO Stability Analysis
figure('Name', 'BIBO Stability Check');
num_stab = [1 -4 3]; 
den_stab = [1 -1.7 1];
N_stab = 200;

% Evaluating absolute summability of the impulse response
h_stab = impz(num_stab, den_stab, N_stab+1);
parsum = 0;

for k = 1:N_stab+1
    parsum = parsum + abs(h_stab(k));
    % System is considered stable if the impulse response decays to zero
    if abs(h_stab(k)) < 10^(-6)
        break; 
    end
end

n_stab = 0:N_stab;
stem(n_stab, h_stab, 'filled');
xlabel('Time index n'); 
ylabel('Amplitude');
title('Impulse Response for Stability Analysis');
grid on;

% Output final stability conclusion to the command window
disp('--- Stability Check ---');
disp(['Absolute Value of last computed sample = ', num2str(abs(h_stab(k)))]);
if abs(h_stab(k)) >= 10^(-6)
    disp('Conclusion: UNSTABLE. The impulse response does not converge due to poles outside the unit circle.');
else
    disp('Conclusion: STABLE.');
end